server:
  port: 8443 # if port is set to 0, spring will choose one that is available.
spring: 
  # jpa:
    # hibernate: 
      # ddl-auto: create
  datasource: 
    url: jdbc:mysql://localhost:3306/tacocloud
    username: tacodb
    password: tacopw
    # driver-class-name: com.mysql.jdbc.Driver # optional 
    # schema:  # optional, since these scripts are scanned automatically
    # - schema.sql 
    # data:
    # - data.sql
    # jndi-name: java:/comp/env/jdbc/tacoCloudDs # Use JDNI, this will overrides all config above 
# logging:
  # level:
    # root: WARN
    # org.springframework.security: DEBUG
    # path: /var/logs  
    # file: tacocloud.log # write to specific file 