# To activate one or more profiles, do it like this: 
#   "java -jar target/taco-cloud-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod" 
# Instead of having multiple profiles in one application.yml, we can have multiple .yml file, 
# where each represents a profile. 
# e.g., application-test.yml, application-prod.yml, etc.

spring: #  configure RabbitMQ (AMQP)
  rabbitmq: 
    host: rabbit.tacocloud.com
    port: 5673
    username: tacoweb
    password: 13tm31n
    template: # configure default exchange and routing 
      exchange: tacocloud.orders
      routing-key: kitchens.central
      receive-timeout: 30000 # block and wait for messaging for N ms
---

# configuration for "prod" profile
server:
  port: 8080 # if port is set to 0, spring will choose one that is available.
spring: 
  # jpa:
    # hibernate: 
      # ddl-auto: create
  profiles: prod
  datasource: 
    url: jdbc:mysql://localhost:3306/tacocloud
    username: tacodb
    password: tacopw

--- 

# default profile 
server:
  port: 8080 
spring:   
  jpa:
    hibernate: 
      ddl-auto: create
  profiles: default 
  datasource: 
    url: jdbc:h2:mem:dev_tacocloud
    username: tacodb
    password: tacopw